image: node:12
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none  
  script:
    - mv public public
  only:
    - master
  artifacts:
    paths:
      - public
