image: node:12
stages:
  - build

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm

before_script:
  - npm ci --cache .npm --prefer-offline

pages:
  stage: build
  variables:
    PUBLIC_URL: https://yulya96gvozdeva96.gitlab.io/weather-forecast
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - public

test_linter:
  stage: test
  script:
    - npm run lint