image: node:12
stages:
  - deploy

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  only:
    - master
  artifacts:
    paths:
      - public