image: node:12
stages:
  - build
  - deploy

build:
  stage: build
  variables:
    PUBLIC_URL: https://gitlab.com/yulya96gvozdeva96/weather-forecast
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  only:
    - master
  artifacts:
    paths:
      - public
