image: node:12
stages:
  - build
  # - test
  - deploy
  
# cache:
#   key: $CI_COMMIT_REF_SLUG
#   paths:
#     - .npm

# before_script:
#   - npm ci --cache .npm --prefer-offline

build:
  stage: build
  variables:
    PUBLIC_URL: https://yulya96gvozdeva96.gitlab.io/weather-forecast
  script:
    - npm run build
  artifacts:
    paths:
      - build

# test_linter:
#   stage: test
#   script:
#     - npm run lint

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public
  artifacts:
    paths:
      - public
